({
    block: 'page',
    title: 'Yeoman BEM',
    favicon: '/favicon.ico',
    head: [
        { elem: 'css', url: '<%= projectStyles %>', ie: false },
        { elem: 'meta', attrs: { name: 'description', content: '' }}
    ],
    content:[
        {
            elem: 'header',
            tag: 'header',
            content: [
                {
                    block: 'title',
                    tag: 'h2',
                    content: [
                        'Hello! This page generated by Yeoman generator-bem.'
                    ]
                }
            ]
        },
        {
            elem: 'content',
            tag: 'main',
            attrs: { role: 'main' },
            content: [
                'Find this in <%= projectBundles %>/index/index.bemjson.js'
            ]
        },
        {
            elem: 'footer',
            tag: 'footer',
            content: [
                'License: ',
                {
                    block: 'link',
                    url: 'http://opensource.org/licenses/MIT',
                    content: [
                        'MIT'
                    ]
                }
            ]
        },
        { elem: 'js', url: '<%= projectScripts %>' }
    ]
})