({
    block : 'page',
    title : 'Yeoman BEM',
    favicon : 'favicon.ico',
    head : [{ elem : 'meta', attrs : { name : 'viewport', content : 'width=device-width, initial-scale=1.0' }}],
    styles : [{ elem : 'css', url : '<%= settings.assets.name %>/<%= settings.assets.styles.name %>' }],
    content : [
        {
            elem : 'header',
            tag : 'header',
            content : [
                {
                    tag : 'h2', content : 'Hello, World! This page generated by Yeoman generator-bem.'
                }
            ]
        },
        {
            elem : 'content',
            tag : 'main',
            attrs : { role: 'main' },
            content : [
                {
                    tag : 'p', content : 'Find this in <%= settings.platform %>.bundles/index/index.bemjson.js'
                }
            ]
        },
        {
            elem : 'footer',
            tag : 'footer',
            content : [
                'License: ',
                {
                    block : 'link',
                    url : 'http://opensource.org/licenses/MIT',
                    content : 'MIT'
                }
            ]
        }
    ],
    scripts : [
        { elem : 'js', url : '<%= settings.assets.name %>/<%= settings.assets.scripts.name %>' }
    ]
})
